require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DependentRelationshipsController do

  # This should return the minimal set of attributes required to create a valid
  # DependentRelationship. As you add validations to DependentRelationship, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "parent_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DependentRelationshipsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all dependent_relationships as @dependent_relationships" do
      dependent_relationship = DependentRelationship.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dependent_relationships).should eq([dependent_relationship])
    end
  end

  describe "GET show" do
    it "assigns the requested dependent_relationship as @dependent_relationship" do
      dependent_relationship = DependentRelationship.create! valid_attributes
      get :show, {:id => dependent_relationship.to_param}, valid_session
      assigns(:dependent_relationship).should eq(dependent_relationship)
    end
  end

  describe "GET new" do
    it "assigns a new dependent_relationship as @dependent_relationship" do
      get :new, {}, valid_session
      assigns(:dependent_relationship).should be_a_new(DependentRelationship)
    end
  end

  describe "GET edit" do
    it "assigns the requested dependent_relationship as @dependent_relationship" do
      dependent_relationship = DependentRelationship.create! valid_attributes
      get :edit, {:id => dependent_relationship.to_param}, valid_session
      assigns(:dependent_relationship).should eq(dependent_relationship)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DependentRelationship" do
        expect {
          post :create, {:dependent_relationship => valid_attributes}, valid_session
        }.to change(DependentRelationship, :count).by(1)
      end

      it "assigns a newly created dependent_relationship as @dependent_relationship" do
        post :create, {:dependent_relationship => valid_attributes}, valid_session
        assigns(:dependent_relationship).should be_a(DependentRelationship)
        assigns(:dependent_relationship).should be_persisted
      end

      it "redirects to the created dependent_relationship" do
        post :create, {:dependent_relationship => valid_attributes}, valid_session
        response.should redirect_to(DependentRelationship.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dependent_relationship as @dependent_relationship" do
        # Trigger the behavior that occurs when invalid params are submitted
        DependentRelationship.any_instance.stub(:save).and_return(false)
        post :create, {:dependent_relationship => { "parent_id" => "invalid value" }}, valid_session
        assigns(:dependent_relationship).should be_a_new(DependentRelationship)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DependentRelationship.any_instance.stub(:save).and_return(false)
        post :create, {:dependent_relationship => { "parent_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dependent_relationship" do
        dependent_relationship = DependentRelationship.create! valid_attributes
        # Assuming there are no other dependent_relationships in the database, this
        # specifies that the DependentRelationship created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DependentRelationship.any_instance.should_receive(:update_attributes).with({ "parent_id" => "1" })
        put :update, {:id => dependent_relationship.to_param, :dependent_relationship => { "parent_id" => "1" }}, valid_session
      end

      it "assigns the requested dependent_relationship as @dependent_relationship" do
        dependent_relationship = DependentRelationship.create! valid_attributes
        put :update, {:id => dependent_relationship.to_param, :dependent_relationship => valid_attributes}, valid_session
        assigns(:dependent_relationship).should eq(dependent_relationship)
      end

      it "redirects to the dependent_relationship" do
        dependent_relationship = DependentRelationship.create! valid_attributes
        put :update, {:id => dependent_relationship.to_param, :dependent_relationship => valid_attributes}, valid_session
        response.should redirect_to(dependent_relationship)
      end
    end

    describe "with invalid params" do
      it "assigns the dependent_relationship as @dependent_relationship" do
        dependent_relationship = DependentRelationship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DependentRelationship.any_instance.stub(:save).and_return(false)
        put :update, {:id => dependent_relationship.to_param, :dependent_relationship => { "parent_id" => "invalid value" }}, valid_session
        assigns(:dependent_relationship).should eq(dependent_relationship)
      end

      it "re-renders the 'edit' template" do
        dependent_relationship = DependentRelationship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DependentRelationship.any_instance.stub(:save).and_return(false)
        put :update, {:id => dependent_relationship.to_param, :dependent_relationship => { "parent_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dependent_relationship" do
      dependent_relationship = DependentRelationship.create! valid_attributes
      expect {
        delete :destroy, {:id => dependent_relationship.to_param}, valid_session
      }.to change(DependentRelationship, :count).by(-1)
    end

    it "redirects to the dependent_relationships list" do
      dependent_relationship = DependentRelationship.create! valid_attributes
      delete :destroy, {:id => dependent_relationship.to_param}, valid_session
      response.should redirect_to(dependent_relationships_url)
    end
  end

end
