require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SimpleValuesController do

  # This should return the minimal set of attributes required to create a valid
  # SimpleValue. As you add validations to SimpleValue, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "value" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SimpleValuesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all simple_values as @simple_values" do
      simple_value = SimpleValue.create! valid_attributes
      get :index, {}, valid_session
      assigns(:simple_values).should eq([simple_value])
    end
  end

  describe "GET show" do
    it "assigns the requested simple_value as @simple_value" do
      simple_value = SimpleValue.create! valid_attributes
      get :show, {:id => simple_value.to_param}, valid_session
      assigns(:simple_value).should eq(simple_value)
    end
  end

  describe "GET new" do
    it "assigns a new simple_value as @simple_value" do
      get :new, {}, valid_session
      assigns(:simple_value).should be_a_new(SimpleValue)
    end
  end

  describe "GET edit" do
    it "assigns the requested simple_value as @simple_value" do
      simple_value = SimpleValue.create! valid_attributes
      get :edit, {:id => simple_value.to_param}, valid_session
      assigns(:simple_value).should eq(simple_value)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SimpleValue" do
        expect {
          post :create, {:simple_value => valid_attributes}, valid_session
        }.to change(SimpleValue, :count).by(1)
      end

      it "assigns a newly created simple_value as @simple_value" do
        post :create, {:simple_value => valid_attributes}, valid_session
        assigns(:simple_value).should be_a(SimpleValue)
        assigns(:simple_value).should be_persisted
      end

      it "redirects to the created simple_value" do
        post :create, {:simple_value => valid_attributes}, valid_session
        response.should redirect_to(SimpleValue.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved simple_value as @simple_value" do
        # Trigger the behavior that occurs when invalid params are submitted
        SimpleValue.any_instance.stub(:save).and_return(false)
        post :create, {:simple_value => { "value" => "invalid value" }}, valid_session
        assigns(:simple_value).should be_a_new(SimpleValue)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SimpleValue.any_instance.stub(:save).and_return(false)
        post :create, {:simple_value => { "value" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested simple_value" do
        simple_value = SimpleValue.create! valid_attributes
        # Assuming there are no other simple_values in the database, this
        # specifies that the SimpleValue created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SimpleValue.any_instance.should_receive(:update_attributes).with({ "value" => "MyString" })
        put :update, {:id => simple_value.to_param, :simple_value => { "value" => "MyString" }}, valid_session
      end

      it "assigns the requested simple_value as @simple_value" do
        simple_value = SimpleValue.create! valid_attributes
        put :update, {:id => simple_value.to_param, :simple_value => valid_attributes}, valid_session
        assigns(:simple_value).should eq(simple_value)
      end

      it "redirects to the simple_value" do
        simple_value = SimpleValue.create! valid_attributes
        put :update, {:id => simple_value.to_param, :simple_value => valid_attributes}, valid_session
        response.should redirect_to(simple_value)
      end
    end

    describe "with invalid params" do
      it "assigns the simple_value as @simple_value" do
        simple_value = SimpleValue.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SimpleValue.any_instance.stub(:save).and_return(false)
        put :update, {:id => simple_value.to_param, :simple_value => { "value" => "invalid value" }}, valid_session
        assigns(:simple_value).should eq(simple_value)
      end

      it "re-renders the 'edit' template" do
        simple_value = SimpleValue.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SimpleValue.any_instance.stub(:save).and_return(false)
        put :update, {:id => simple_value.to_param, :simple_value => { "value" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested simple_value" do
      simple_value = SimpleValue.create! valid_attributes
      expect {
        delete :destroy, {:id => simple_value.to_param}, valid_session
      }.to change(SimpleValue, :count).by(-1)
    end

    it "redirects to the simple_values list" do
      simple_value = SimpleValue.create! valid_attributes
      delete :destroy, {:id => simple_value.to_param}, valid_session
      response.should redirect_to(simple_values_url)
    end
  end

end
